- id: KuaiFan.DooTask
  enable: true
  type: Github
  url: https://api.github.com/repos/kuaifan/dootask/releases/latest
  match:
    requiredKeywords:
      - .exe
    excludedKeywords:
      - .blockmap
  version:
    removeFirstCharacter: true
- id: listen1.listen1
  enable: true
  type: Github
  url: https://api.github.com/repos/listen1/listen1_desktop/releases/latest
  match:
    requiredKeywords:
      - .exe
    excludedKeywords:
      - blockmap
    necessaryKeywords:
      - ia32
      - x64
      - arm64
  version:
    removeFirstCharacter: true
- id: PicGo.PicGo
  enable: true
  type: Github
  url: https://api.github.com/repos/Molunerfinn/PicGo/releases/latest
  match:
    requiredKeywords:
      - .exe
    excludedKeywords:
      - blockmap
    necessaryKeywords:
      - ia32
      - x64
  version:
    removeFirstCharacter: true
- id: PicGo.PicGo.Beta
  type: Github
  enable: true
  url: https://api.github.com/repos/Molunerfinn/PicGo/releases
  skip:
    whenEqualsToLatestVersion:
      enable: true
      url: https://api.github.com/repos/Molunerfinn/PicGo/releases/latest
      path: tag_name
  assets:
    index: 0
  match:
    requiredKeywords:
      - .exe
    excludedKeywords:
      - blockmap
    necessaryKeywords:
      - ia32
      - x64
  version:
    removeFirstCharacter: true