name: Auto Publish
on:
  workflow_dispatch:
  schedule: [{ cron: 0 * * * * }]

env:
  NAME: "CoolPlayLinBot"
  EMAIL: "130831920+coolplaylinbot@users.noreply.github.com"

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2
        with:
          token: ${{ secrets.COOLPLAYLIN_BOT_TOKEN }}
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Setup Node.JS
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: pnpm/action-setup@v3
        name: Install pnpm
        with:
          version: 8
          run_install: false
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Setup Git Info
        run: |
          git config --global user.name "${{ env.NAME }}"
          git config --global user.email "${{ env.EMAIL }}"
      - name: Install Dependencies
        run: |
          python3 -m pip install -r requirements.txt
          pnpm install
      - name: Publish
        run: python3 src/main.py
        env:
          TOKEN: ${{ secrets.TOKEN }}
      - name: Format
        run: npm run format
      - name: Post on Always
        if: always()
        shell: pwsh
        run: |
          if (git status -s){
            git add .
            git commit -m "Update metadata"
            git push origin --force
          }
