name: Auto Publish
on:
 workflow_dispatch:
 schedule: [{cron: 0 * * * *}]

env:
  NAME: "CoolPlayLinBot"
  EMAIL: "130831920+coolplaylinbot@users.noreply.github.com"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
        with:
          token: ${{ secrets.COOLPLAYLIN_BOT_TOKEN }}
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.0'
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      - name: Setup Node.JS
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
      - name: Setup Env
        run: |
          python3 -m pip install -r requirements.txt
          npm install
          git config --global user.name "${{ env.NAME }}"
          git config --global user.email "${{ env.EMAIL }}"
      - name: Publish
        run: python3 src/main.py ${{ secrets.TOKEN }}
      - name: Format
        run: npm run format
      - name: Post on Always
        if: always()
        run: |
            if [[ -n $(git status -s) ]]; then
            git add .
            git commit -m "Update metadata"
            git push origin --force
            fi